'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Globalization
Imports System.Resources
Imports System.Runtime.CompilerServices

Namespace My.Resources

    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),
     DebuggerNonUserCode(),
     CompilerGenerated(),
     HideModuleName()>
    Public Module Resources

        Private resourceMan As ResourceManager

        Private resourceCulture As CultureInfo

        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>
        Public ReadOnly Property ResourceManager() As ResourceManager
            Get
                If ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As ResourceManager = New ResourceManager("MikuWeather.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>
        Public Property Culture() As CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property abc_ic_cab_done_holo_dark() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abc_ic_cab_done_holo_dark", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property abc_ic_clear_disabled() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abc_ic_clear_disabled", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property abc_ic_clear_disabled1() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abc_ic_clear_disabled1", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property abc_ic_clear_normal() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abc_ic_clear_normal", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property action_title() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("action_title", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property bg_btn() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_btn", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property bg_wdt() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_wdt", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property bg_wdtb() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_wdtb", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property bg_weather() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_weather", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property hi() As Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("hi", resourceCulture)
                Return CType(obj, Icon)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property ic_menu_refresh() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_refresh", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property juhe() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("juhe", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property liantu() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liantu", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property loc() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loc", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property logo() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property N1() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N1", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property N2() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N2", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property noloc() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noloc", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property QRcode() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QRcode", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property U() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("U", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 中雨() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("中雨", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 夜多云() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("夜多云", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 夜晴() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("夜晴", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 夜雨1() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("夜雨1", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 夜雪() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("夜雪", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 夜雷阵雨() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("夜雷阵雨", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 大雨() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大雨", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 小雨() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小雨", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 日多云() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("日多云", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 日雪() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("日雪", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 晴() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("晴", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 暴雪() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("暴雪", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 阴() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阴", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 阴雨() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阴雨", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 雨夹雪() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雨夹雪", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 雪() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雪", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 雷阵雨() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雷阵雨", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property 雾() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雾", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property
    End Module
End Namespace
